<?php 

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_digital-page-sections',
    'title' => 'Digital Page Sections',
    'fields' => array (
      array (
        'key' => 'field_57f9721393682',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'instructions' => 'Optional description field. Formatting will convert HTML into tags.',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 4,
        'formatting' => 'html',
      ),
      array (
        'key' => 'field_57f9724393683',
        'label' => 'Body Content',
        'name' => 'body_content',
        'type' => 'wysiwyg',
        'instructions' => 'This field will accept plain text, formatted text, and HTML markup. Wrap inline elements in classless div to prevent auto p and br tags.',
        'required' => 1,
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_57f9726e93684',
        'label' => 'Section ID',
        'name' => 'id',
        'type' => 'text',
        'instructions' => 'A unique ID is needed for the sidebar anchor list. Whitespace is not allowed. The ID must be lowercased and as few words as possible. If the ID is more than one word it must be a hyphenated compound.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f974f593685',
        'label' => 'Class List',
        'name' => 'class_list',
        'type' => 'text',
        'instructions' => 'Add classes to extend predefined style rules. Consider object oriented CSS. Class names are separated by whitespace.',
        'default_value' => '',
        'placeholder' => '(e.g. has-dropshadow)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f976a993852',
        'label' => 'Sidebar Text',
        'name' => 'sidebar_text',
        'type' => 'text',
        'instructions' => 'This is the anchor / link text that gets appended to the sidebar. Be as concise as possible.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f9773ff061a',
        'label' => 'Download Link',
        'name' => 'download_link',
        'type' => 'text',
        'instructions' => 'Add URI to a downloadable file. Zip files are currently preferred.',
        'default_value' => '',
        'placeholder' => '(e.g. https://www.dropbox.com/downloadable-file.zip?dl=0)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'digital_pg_sections',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'format',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_digital-resources',
    'title' => 'Digital Resources',
    'fields' => array (
      array (
        'key' => 'field_58005c18d62d6',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'instructions' => 'Optional description field. Formatting will convert HTML into tags.',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 4,
        'formatting' => 'html',
      ),
      array (
        'key' => 'field_58005cc8d62d7',
        'label' => 'Body Content',
        'name' => 'body_content',
        'type' => 'wysiwyg',
        'instructions' => 'This field will accept plain text, formatted text, and HTML markup. Wrap inline elements in classless div to prevent auto p and br tags.',
        'required' => 1,
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_58005d32d62d8',
        'label' => 'Section ID',
        'name' => 'id',
        'type' => 'text',
        'instructions' => 'A unique ID is needed for the sidebar anchor list. Whitespace is not allowed. The ID must be lowercased and as few words as possible. If the ID is more than one word it must be a hyphenated compound.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_58005d94d62d9',
        'label' => 'Class List',
        'name' => 'class_list',
        'type' => 'text',
        'instructions' => 'Add classes to extend predefined style rules. Consider object oriented CSS. Class names are separated by whitespace.',
        'default_value' => '',
        'placeholder' => '(e.g. has-dropshadow)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_58005e06d62da',
        'label' => 'Sidebar Text',
        'name' => 'sidebar_text',
        'type' => 'text',
        'instructions' => 'This is the anchor / link text that gets appended to the sidebar. Be as concise as possible.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_58005ed9d62db',
        'label' => 'Download Link',
        'name' => 'download_link',
        'type' => 'text',
        'instructions' => ' Add URI to a downloadable file. Zip files are currently preferred.',
        'default_value' => '',
        'placeholder' => '(e.g. https://www.dropbox.com/downloadable-file.zip?dl=0)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'digital_resources',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'format',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_digital-templates',
    'title' => 'Digital Templates',
    'fields' => array (
      array (
        'key' => 'field_580053c3fd9bf',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'instructions' => 'Optional description field. Formatting will convert HTML into tags.',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 4,
        'formatting' => 'html',
      ),
      array (
        'key' => 'field_5800549afd9c0',
        'label' => 'Body Content',
        'name' => 'body_content',
        'type' => 'wysiwyg',
        'instructions' => 'This field will accept plain text, formatted text, and HTML markup. Wrap inline elements in classless div to prevent auto p and br tags.',
        'required' => 1,
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_58005543fd9c1',
        'label' => 'Section ID',
        'name' => 'id',
        'type' => 'text',
        'instructions' => 'A unique ID is needed for the sidebar anchor list. Whitespace is not allowed. The ID must be lowercased and as few words as possible. If the ID is more than one word it must be a hyphenated compound.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5800557dfd9c2',
        'label' => 'Class List',
        'name' => 'class_list',
        'type' => 'text',
        'instructions' => 'Add classes to extend predefined style rules. Consider object oriented CSS. Class names are separated by whitespace.',
        'default_value' => '',
        'placeholder' => '(e.g. has-dropshadow)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_580055bdfd9c3',
        'label' => 'Sidebar Text',
        'name' => 'sidebar_text',
        'type' => 'text',
        'instructions' => 'This is the anchor / link text that gets appended to the sidebar. Be as concise as possible.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_580055e7fd9c4',
        'label' => 'Download Link',
        'name' => 'download_link',
        'type' => 'text',
        'instructions' => 'Add URI to a downloadable file. Zip files are currently preferred.',
        'default_value' => '',
        'placeholder' => '(e.g. https://www.dropbox.com/downloadable-file.zip?dl=0)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'digital_templates',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'format',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_digital-components',
    'title' => 'Digital Components',
    'fields' => array (
      array (
        'key' => 'field_57ff5ce448ac3',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'instructions' => 'Optional description field. Formatting will convert HTML into tags.',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 4,
        'formatting' => 'html',
      ),
      array (
        'key' => 'field_57ff5d2748ac4',
        'label' => 'Body Content',
        'name' => 'body_content',
        'type' => 'wysiwyg',
        'instructions' => 'This field will accept plain text, formatted text, and HTML markup. Wrap inline elements in classless div to prevent auto p and br tags.',
        'required' => 1,
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_57ff5d5548ac5',
        'label' => 'Section ID',
        'name' => 'id',
        'type' => 'text',
        'instructions' => 'A unique ID is needed for the sidebar anchor list. Whitespace is not allowed. The ID must be lowercased and as few words as possible. If the ID is more than one word it must be a hyphenated compound.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57ff5db348ac6',
        'label' => 'Class List',
        'name' => 'class_list',
        'type' => 'text',
        'instructions' => 'Add classes to extend predefined style rules. Consider object oriented CSS. Class names are separated by whitespace.',
        'default_value' => '',
        'placeholder' => '(e.g. has-dropshadow)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57ff5f8e48ac7',
        'label' => 'Sidebar Text',
        'name' => 'sidebar_text',
        'type' => 'text',
        'instructions' => 'This is the anchor / link text that gets appended to the sidebar. Be as concise as possible.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57ff603348ac8',
        'label' => 'Download Link',
        'name' => 'download_link',
        'type' => 'text',
        'instructions' => 'Add URI to a downloadable file. Zip files are currently preferred.',
        'default_value' => '',
        'placeholder' => '(e.g. https://www.dropbox.com/downloadable-file.zip?dl=0)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'digital_components',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'format',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_digital-elements',
    'title' => 'Digital Elements',
    'fields' => array (
      array (
        'key' => 'field_57ff32bf4d37f',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'instructions' => 'Optional description field. Formatting will convert HTML into tags.',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 4,
        'formatting' => 'html',
      ),
      array (
        'key' => 'field_57ff33274d380',
        'label' => 'Body Content',
        'name' => 'body_content',
        'type' => 'wysiwyg',
        'instructions' => 'This field will accept plain text, formatted text, and HTML markup. Wrap inline elements in classless div to prevent auto p and br tags.',
        'required' => 1,
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_57ff33964d381',
        'label' => 'Section ID',
        'name' => 'id',
        'type' => 'text',
        'instructions' => 'A unique ID is needed for the sidebar anchor list. Whitespace is not allowed. The ID must be lowercased and as few words as possible. If the ID is more than one word it must be a hyphenated compound.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57ff340b4d382',
        'label' => 'Class List',
        'name' => 'class_list',
        'type' => 'text',
        'instructions' => 'Add classes to extend predefined style rules. Consider object oriented CSS. Class names are separated by whitespace.',
        'default_value' => '',
        'placeholder' => '(e.g. has-dropshadow)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57ff345c4d383',
        'label' => 'Sidebar Text',
        'name' => 'sidebar_text',
        'type' => 'text',
        'instructions' => 'This is the anchor / link text that gets appended to the sidebar. Be as concise as possible.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57ff349b4d384',
        'label' => 'Download Link',
        'name' => 'download_link',
        'type' => 'text',
        'instructions' => 'Add URI to a downloadable file. Zip files are currently preferred.',
        'default_value' => '',
        'placeholder' => '(e.g. https://www.dropbox.com/downloadable-file.zip?dl=0)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'digital_elements',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'format',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_print-page-sections',
    'title' => 'Print Page Sections',
    'fields' => array (
      array (
        'key' => 'field_57f98a6433610',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'instructions' => 'Optional description field. Formatting will convert HTML into tags.',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 4,
        'formatting' => 'html',
      ),
      array (
        'key' => 'field_57f98ade33611',
        'label' => 'Body Content',
        'name' => 'body_content',
        'type' => 'wysiwyg',
        'instructions' => 'This field will accept plain text, formatted text, and HTML markup. Wrap inline elements in classless div to prevent auto p and br tags.',
        'required' => 1,
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_57f98b2933612',
        'label' => 'Section ID',
        'name' => 'id',
        'type' => 'text',
        'instructions' => 'A unique ID is needed for the sidebar anchor list. Whitespace is not allowed. The ID must be lowercased and as few words as possible. If the ID is more than one word it must be a hyphenated compound.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f98b6a33613',
        'label' => 'Class List',
        'name' => 'class_list',
        'type' => 'text',
        'instructions' => 'Add classes to extend predefined style rules. Consider object oriented CSS. Class names are separated by whitespace.',
        'default_value' => '',
        'placeholder' => '(e.g. has-dropshadow)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f98b9233614',
        'label' => 'Sidebar Text',
        'name' => 'sidebar_text',
        'type' => 'text',
        'instructions' => 'This is the anchor / link text that gets appended to the sidebar. Be as concise as possible.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f98bbb33615',
        'label' => 'Download Link',
        'name' => 'download_link',
        'type' => 'text',
        'instructions' => 'Add URI to a downloadable file. Zip files are currently preferred.',
        'default_value' => '',
        'placeholder' => '(e.g. https://www.dropbox.com/downloadable-file.zip?dl=0)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'print_page_sections',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'format',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_homepage-sections',
    'title' => 'Homepage Sections',
    'fields' => array (
      array (
        'key' => 'field_57f666062d473',
        'label' => 'Section One Title',
        'name' => 'section_one_title',
        'type' => 'text',
        'required' => 1,
        'default_value' => '',
        'placeholder' => 'Digital',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f66e43ba5b7',
        'label' => 'Section One Anchor',
        'name' => 'section_one_anchor',
        'type' => 'text',
        'instructions' => 'Enter page this section links to',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f674d942ccd',
        'label' => 'Section One Blurb',
        'name' => 'section_one_blurb',
        'type' => 'text',
        'instructions' => 'Section blurb',
        'default_value' => '',
        'placeholder' => 'UI and UX area',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f675b942cd0',
        'label' => 'Section One BGimg',
        'name' => 'section_one_bgimg',
        'type' => 'file',
        'instructions' => 'Section background image',
        'required' => 1,
        'save_format' => 'url',
        'library' => 'all',
      ),
      array (
        'key' => 'field_57f863603824b',
        'label' => 'Section One CTA',
        'name' => 'section_one_cta',
        'type' => 'text',
        'instructions' => 'Enter brief CTA text',
        'default_value' => 'go to resources',
        'placeholder' => '(e.g. Learn More ->)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f66703e97df',
        'label' => 'Section Two Title',
        'name' => 'section_two_title',
        'type' => 'text',
        'instructions' => 'Title for section two',
        'required' => 1,
        'default_value' => '',
        'placeholder' => 'Print',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f6751942cce',
        'label' => 'Section Two Blurb',
        'name' => 'section_two_blurb',
        'type' => 'text',
        'instructions' => 'Section blurb',
        'default_value' => '',
        'placeholder' => 'Print and Design area',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f6761542cd1',
        'label' => 'Section Two BGimg',
        'name' => 'section_two_bgimg',
        'type' => 'file',
        'instructions' => 'Section background image',
        'required' => 1,
        'save_format' => 'url',
        'library' => 'all',
      ),
      array (
        'key' => 'field_57f863eb3824c',
        'label' => 'Section Two CTA',
        'name' => 'section_two_cta',
        'type' => 'text',
        'instructions' => 'Enter brief CTA text',
        'default_value' => 'go to resources',
        'placeholder' => '(e.g. Learn More ->)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f66ea3ba5b9',
        'label' => 'Section Two Anchor',
        'name' => 'section_two_anchor',
        'type' => 'text',
        'instructions' => 'Enter page this section links to',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f667d75b198',
        'label' => 'Section Three Title',
        'name' => 'section_three_title',
        'type' => 'text',
        'instructions' => 'Title for section three',
        'required' => 1,
        'default_value' => '',
        'placeholder' => 'On-Air',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f66ecaba5ba',
        'label' => 'Section Three Anchor',
        'name' => 'section_three_anchor',
        'type' => 'text',
        'instructions' => 'Enter page this section links to',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f6756442ccf',
        'label' => 'Section Three Blurb',
        'name' => 'section_three_blurb',
        'type' => 'text',
        'instructions' => 'Section blurb',
        'default_value' => '',
        'placeholder' => 'Footage and Graphics area',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f6763042cd2',
        'label' => 'Section Three BGimg',
        'name' => 'section_three_bgimg',
        'type' => 'file',
        'instructions' => 'Section background image',
        'required' => 1,
        'save_format' => 'url',
        'library' => 'all',
      ),
      array (
        'key' => 'field_57f864043824d',
        'label' => 'Section Three CTA',
        'name' => 'section_three_cta',
        'type' => 'text',
        'instructions' => 'Enter brief CTA text',
        'default_value' => 'go to resources',
        'placeholder' => '(e.g. Learn More ->)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'home_page_sections',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
        0 => 'permalink',
        1 => 'the_content',
        2 => 'excerpt',
        3 => 'custom_fields',
        4 => 'discussion',
        5 => 'comments',
        6 => 'revisions',
        7 => 'slug',
        8 => 'author',
        9 => 'format',
        10 => 'featured_image',
        11 => 'categories',
        12 => 'tags',
        13 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_on-air-demos',
    'title' => 'On-Air Demos',
    'fields' => array (
      array (
        'key' => 'field_57f64c201166e',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'instructions' => 'Optional description field. Formatting will convert HTML into tags.',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 4,
        'formatting' => 'html',
      ),
      array (
        'key' => 'field_57f64c601166f',
        'label' => 'Body Content',
        'name' => 'body_content',
        'type' => 'wysiwyg',
        'instructions' => 'This field will accept plain text, formatted text, and HTML markup. Wrap inline elements in classless div to prevent auto p and br tags.',
        'required' => 1,
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_57f64cb711670',
        'label' => 'Section ID',
        'name' => 'id',
        'type' => 'text',
        'instructions' => 'A unique ID is needed for the sidebar anchor list. Whitespace is not allowed. The ID must be lowercased and as few words as possible. If the ID is more than one word it must be a hyphenated compound.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f64ceb11671',
        'label' => 'Class List',
        'name' => 'class_list',
        'type' => 'text',
        'instructions' => 'Add classes to extend predefined style rules. Consider object oriented CSS. Class names are separated by whitespace.',
        'default_value' => '',
        'placeholder' => '(e.g. has-dropshadow)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f64d3111672',
        'label' => 'Sidebar Text',
        'name' => 'sidebar_text',
        'type' => 'text',
        'instructions' => 'This is the anchor / link text that gets appended to the sidebar. Be as concise as possible.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f64d6e11673',
        'label' => 'Download Link',
        'name' => 'download_link',
        'type' => 'text',
        'instructions' => 'Add URI to a downloadable file. Zip files are currently preferred.',
        'default_value' => '',
        'placeholder' => '(e.g. https://www.dropbox.com/downloadable-file.zip?dl=0)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'onair_demos',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'format',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_on-air-structures',
    'title' => 'On-Air Structures',
    'fields' => array (
      array (
        'key' => 'field_57f2d518a6b7a',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'instructions' => 'Optional description field. Formatting will convert HTML into tags.',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 4,
        'formatting' => 'html',
      ),
      array (
        'key' => 'field_57f2d540a6b7b',
        'label' => 'Body Content',
        'name' => 'body_content',
        'type' => 'wysiwyg',
        'instructions' => 'This field will accept plain text, formatted text, and HTML markup. Wrap inline elements in classless div to prevent auto p and br tags.',
        'required' => 1,
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_57f2d569a6b7c',
        'label' => 'Section ID',
        'name' => 'id',
        'type' => 'text',
        'instructions' => 'A unique ID is needed for the sidebar anchor list. Whitespace is not allowed. The ID must be lowercased and as few words as possible. If the ID is more than one word it must be a hyphenated compound.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f62694d53f8',
        'label' => 'Class List',
        'name' => 'class_list',
        'type' => 'text',
        'instructions' => 'Add classes to extend predefined style rules. Consider object oriented CSS. Class names are separated by whitespace.',
        'default_value' => '',
        'placeholder' => '(e.g. has-dropshadow)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57fab7f4abd39',
        'label' => 'Sidebar Text',
        'name' => 'sidebar_text',
        'type' => 'text',
        'instructions' => 'This is the anchor / link text that gets appended to the sidebar. Be as concise as possible.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f2ee329ae24',
        'label' => 'Download Link',
        'name' => 'download_link',
        'type' => 'text',
        'instructions' => 'Add URI to a downloadable file. Zip files are currently preferred.',
        'default_value' => '',
        'placeholder' => '(e.g. https://www.dropbox.com/downloadable-file.zip?dl=0)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'onair_structures',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'format',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_on-air-elements',
    'title' => 'On-Air Elements',
    'fields' => array (
      array (
        'key' => 'field_57f2937af6729',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'instructions' => 'Optional description field. Formatting will convert HTML into tags.',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 4,
        'formatting' => 'html',
      ),
      array (
        'key' => 'field_57f2938bf672a',
        'label' => 'Body Content',
        'name' => 'body_content',
        'type' => 'wysiwyg',
        'instructions' => 'This field will accept plain text, formatted text, and HTML markup. Wrap inline elements in classless div to prevent auto p and br tags.',
        'required' => 1,
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_57f293c7f672b',
        'label' => 'Section ID',
        'name' => 'id',
        'type' => 'text',
        'instructions' => 'A unique ID is needed for the sidebar anchor list. Whitespace is not allowed. The ID must be lowercased and as few words as possible. If the ID is more than one word it must be a hyphenated compound.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f29405f672c',
        'label' => 'Sidebar Text',
        'name' => 'sidebar_text',
        'type' => 'text',
        'instructions' => 'This is the anchor / link text that gets appended to the sidebar. Be as concise as possible.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f9356a27471',
        'label' => 'Class List',
        'name' => 'class_list',
        'type' => 'text',
        'instructions' => 'Add classes to extend predefined style rules. Consider object oriented CSS. Class names are separated by whitespace.',
        'default_value' => '',
        'placeholder' => '(e.g. has-dropshadow)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f935e727472',
        'label' => 'Download Link',
        'name' => 'download_link',
        'type' => 'text',
        'instructions' => 'Add URI to a downloadable file. Zip files are currently preferred.',
        'default_value' => '',
        'placeholder' => '(e.g. https://www.dropbox.com/downloadable-file.zip?dl=0)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'onair_elements',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'format',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_on-air-page-sections',
    'title' => 'On-Air Page Sections',
    'fields' => array (
      array (
        'key' => 'field_57f282a4351b8',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'instructions' => 'Optional description field. Formatting will convert HTML into tags.',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 4,
        'formatting' => 'html',
      ),
      array (
        'key' => 'field_57f282bd351b9',
        'label' => 'Body Content',
        'name' => 'body_content',
        'type' => 'wysiwyg',
        'instructions' => 'This field will accept plain text, formatted text, and HTML markup. Wrap inline elements in classless div to prevent auto p and br tags.',
        'required' => 1,
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_57f282d9351ba',
        'label' => 'Section ID',
        'name' => 'id',
        'type' => 'text',
        'instructions' => 'A unique ID is needed for the sidebar anchor list. Whitespace is not allowed. The ID must be lowercased and as few words as possible. If the ID is more than one word it must be a hyphenated compound.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f93a69774c7',
        'label' => 'Class List',
        'name' => 'class_list',
        'type' => 'text',
        'instructions' => 'Add classes to extend predefined style rules. Consider object oriented CSS. Class names are separated by whitespace.',
        'default_value' => '',
        'placeholder' => '(e.g. has-dropshadow)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57fdfc580dc77',
        'label' => 'Sidebar Text',
        'name' => 'sidebar_text',
        'type' => 'text',
        'instructions' => 'This is the anchor / link text that gets appended to the sidebar. Be as concise as possible.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_57f93b0c774c8',
        'label' => 'Download Link',
        'name' => 'download_link',
        'type' => 'text',
        'instructions' => 'Add URI to a downloadable file. Zip files are currently preferred.',
        'default_value' => '',
        'placeholder' => '(e.g. https://www.dropbox.com/downloadable-file.zip?dl=0)',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'onair_page_sections',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'format',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_print-elements',
    'title' => 'Print Elements',
    'fields' => array (
      array (
        'key' => 'field_57ede10b84eab',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'instructions' => 'Optional description field. Formatting will convert HTML into tags.',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 4,
        'formatting' => 'html',
      ),
      array (
        'key' => 'field_57ede18884eac',
        'label' => 'snippet',
        'name' => 'snippet',
        'type' => 'wysiwyg',
        'instructions' => 'what you see is what you get',
        'default_value' => '',
        'toolbar' => 'full',
        'media_upload' => 'yes',
      ),
      array (
        'key' => 'field_57ede1fc84ead',
        'label' => 'Section ID',
        'name' => 'id',
        'type' => 'text',
        'instructions' => 'A unique ID is needed for the sidebar anchor list. Whitespace is not allowed. The ID must be lowercased and as few words as possible. If the ID is more than one word it must be a hyphenated compound.',
        'required' => 1,
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'print_elements',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'format',
        6 => 'featured_image',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
}

?>